# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movielisting-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-listing
  template:
    metadata:
      labels:
        app: movie-listing
    spec:
      containers:
      - name: movie-listing-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/$GCLOUD_PROJECT/movielisting-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
